config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]


  # resources :comments

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :projects, only: :index

  resources :articles do
    resources :comments
  end

  get '/about' => 'static#about', as: 'about_me'
  root 'static#index', as: "home"
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/projects_controller.rb
require 'fastimage'

class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @pieces = Array.new

    @projects.each do |project|
      size = FastImage.size "app/assets/images/projects/#{project.pic_url}"
      if !project.pic_url.include? "http:"
        pic = ActionController::Base.helpers.asset_path('projects/' + project.pic_url, type: :image)
      else
        pic = project.pic_url
      end
      @pieces << Array.new([
                  pic,
                  project.site_url,
                  size[0],
                  size[1],
                  project.name,
                  project.categories
                  ])
    end

    @indexes = Array.new
    @design = Array.new
    @code = Array.new
    @ruby = Array.new
    @work = Array.new
    @general = Array.new
    @favorite = Array.new

    @pieces.each_with_index do |piece, index|
      @indexes << index
      @design << index if piece[5].include? "DESIGN"
      @code << index if piece[5].include? "CODE"
      @ruby << index if piece[5].include? "RUBY"
      @work << index if piece[5].include? "WORK"
      @general << index if piece[5].include? "GENERAL"
      @favorite << index if piece[5].include? "FAVORITE"
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    respond_to do |format|
      format.html { }
      format.js { }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    respond_to do |format|
      format.html { @project }
      format.js { @project }
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.js { redirect_to @project }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.js { redirect_to @project }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.js { redirect_to @project }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @id = params[:id]
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.js {  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :pic_url, :site_url, :categories, :technologies_used)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, remote: true do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pic_url %><br>
    <%= f.text_field :pic_url %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :categories %><br>
    <%= f.text_field :categories %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %><br>
    <%= f.text_area :technologies_used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr class="tr<%= project.id %>">
  <td class="name"><%= project.name %></td>
  <td class="content"><%= project.technologies_used %></td>
  <td><%= link_to 'Show', project %></td>
  <td><%= link_to 'Edit', edit_project_path(project), remote: true, class: :edit %></td>
  <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
</tr>

app/views/projects/destroy.js.erb
$('tr.tr<%= @project.id %>').remove();

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit.js.erb
$('#add_project, tr.tr<%= @project.id %> .edit').hide();
$('#all_projects').parent().after(
  "<div id=\"project_form\">" + "<%= j render 'form' %></div>"
);

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<nav id="shuffle-board-nav">
  <div id="all-btn">All</div>
  <div id="design-btn">DESIGN</div>
  <div id="code-btn">CODE</div>
  <div id="ruby-btn">RUBY</div>
  <div id="sesame-btn">WORK</div>
  <div id="general-btn">GENERAL</div>
  <div id="fun-btn">FAVORITE</div>
</nav>

<div id="content" class="container">
  <div id="shuffle-board">
    &nbsp;
  </div>
</div>


<script>
	$(document).ready(function(){
		var pieces = <%= @pieces.to_json.html_safe %>;
		var items = new Array();

		for(var i = 0, l = pieces.length; i < l; i++)
			items.push( new Item(
					pieces[i][0],
					pieces[i][1],
					pieces[i][2],
					pieces[i][3],
					pieces[i][4]
				) );

		indexes = [<%= @indexes %>,
										<%= @design %>,
										<%= @code %>,
										<%= @ruby %>,
										<%= @work %>,
										<%= @general %>,
										<%= @favorite %>];

		var board = new ShuffleBoard(items, indexes);

		$( window ).resize(function(){
			board.resize();
			board.update(0);
		});
	});

</script>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$('#add_project').hide().after(
  "<%= j render 'form' %>"
);

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Technologies used:</strong>
  <%= @project.technologies_used %>
</p>

<%= link_to 'Edit', edit_project_path(@project), remote: true %> |
<%= link_to 'Back', projects_path %>

app/views/projects/show.js.erb
$('#project_form').remove();
$('#add_project').show();
$('tr.tr<%= @project.id %> .name').html( "<%= @project.name %>" );
$('tr.tr<%= @project.id %> .content').html( "<%= j @project.technologies_used %>" );
$('tr.tr<%= @project.id %> .edit').show();