config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]


  # resources :comments

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :projects, only: :index

  resources :articles do
    resources :comments
  end

  get '/about' => 'static#about', as: 'about_me'
  root 'static#index', as: "home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'projects' if params[:controller] == "projects" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'shuffle_board' if params[:controller] == "projects" %>

  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.9.0/bootstrap-social.css">

  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '1582832168631975',
        xfbml      : true,
        version    : 'v2.3'
      });
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>

  <script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : "#{ENV['FACEBOOK_APP_ID']}",
    cookie     : true,  // enable cookies to allow the server to access
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.2
  });

  // Now that we've initialized the JavaScript SDK, we call
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

</head>

<body class="<%= current_tab %>">

<header id="main-header">
  <div id="top-nav" class="container row clearfix">
    <nav id="main-nav" class="col-xs-12 col-sm-5 left xs-text-left">
      <%= link_to "Home", home_path %>
      <%= link_to "About Me", about_me_path %>
      <%= link_to "Projects", projects_path %>
      <%= link_to "Blog", articles_path %>
      <%= link_to "Contact", new_contact_path %>
    </nav>

    <div id="carousel-container">
      <div id="menu-carousel">
        <figure>Email Me</figure>
        <figure>Kevin Townsend</figure>
        <figure>Who am I?</figure>
        <figure>View My Work</figure>
        <figure style="margin-top:-10px;">See what people have to say</figure>
        <figure>Email Me</figure>
        <figure>Kevin Townsend</figure>
      </div>
    </div>

    <div id="user-name" class="col-xs-3">
      <% if user_signed_in? %>
        Logged in as
        <strong>
          <% if current_user.email %>
            <%= current_user.email %>
          <% elsif current_user.username %>
            <%= current_user.username %>
          <% end %>
        </strong>
      <% end %>
    </div>

    <nav id="sign-in-nav" class="col-xs-12 col-sm-3 right xs-text-right">
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <%= link_to 'Edit profile', edit_user_registration_path %>
      <% else%>
        <%= link_to "Login", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </nav>
  </div>
</header>

<%= yield %>

</body>
</html>